name: C/C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ubuntu-build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Checkout raylib
        uses: actions/checkout@v2.0.0
        with:
          repository: raysan5/raylib
          path: raylib
      - name: Build project
        uses: nicledomaS/cmake_build_action@v1.4
