name: C/C++ CI

on: ["push", "pull_request"]

jobs:
  ubuntu-build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Build project
        uses: nicledomaS/cmake_build_action@v1.4
